version: '3.1'
services:
  mongo:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoroot
      MONGO_INITDB_ROOT_PASSWORD: mongopass
      MONGO_INITDB_DATABASE: book
    ports:
    - 27017:27017
    volumes:
      - ./BookOfAdventure/src/main/docker/mongo/1_init-mongo.js:/docker-entrypoint-initdb.d/BookOfAdventure-1_init-mongo.js:ro
      - ./Dungeon/src/main/docker/mongo/1_init-mongo.js:/docker-entrypoint-initdb.d/Dungeon-1_init-mongo.js:ro
      - ./Dungeon/src/main/docker/mongo/2_insert-data.sh:/docker-entrypoint-initdb.d/Dungeon-2_insert-data.sh:ro
      - ./Dungeon/src/main/docker/mongo/dungeonDomain.json:/docker-entrypoint-initdb.d/dungeonDomain.json:ro
      - ./Objects/src/main/docker/mongo/1_init-mongo.js:/docker-entrypoint-initdb.d/Objects-1_init-mongo.js:ro
      - ./Objects/src/main/docker/mongo/2_insert-data.sh:/docker-entrypoint-initdb.d/Objects-2_insert-data.sh:ro
      - ./Objects/src/main/docker/mongo/armorDomain.json:/docker-entrypoint-initdb.d/armorDomain.json:ro
      - ./Objects/src/main/docker/mongo/ringDomain.json:/docker-entrypoint-initdb.d/ringDomain.json:ro
  mongo-express:
    image: mongo-express
    ports:
      - 8089:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoroot
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopass
    depends_on:
      - mongo
